In [1]:
import pandas as pd
pd.__version__

'2.2.2'

In [2]:
df = pd.read_csv(r"/Users/pavan.garigipati/NIT_DatascienceAndAI/PANDAS/data.csv")
# df = pd.read_csv(r"data.csv")
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [3]:
id(df)

4809303840

In [4]:
len(df)

195

In [5]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [6]:
len(df.columns)

5

In [7]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [8]:
df.isna() # isna() and isnull() both are same

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [9]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [10]:
df.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [11]:
df.isna().count()

CountryName      195
CountryCode      195
BirthRate        195
InternetUsers    195
IncomeGroup      195
dtype: int64

In [12]:
df.head() # head() function prints top 5 rows

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [13]:
df.tail() # tail() function prints bottom 5 rows

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [62]:
df.tail(20)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
175,Tunisia,TUN,19.800,43.80,Upper middle income,867.24000
176,Turkey,TUR,16.836,46.25,Upper middle income,778.66500
177,Tanzania,TZA,39.518,4.40,Low income,173.87920
178,Uganda,UGA,43.474,16.20,Low income,704.27880
179,Ukraine,UKR,11.100,41.00,Lower middle income,455.10000
180,Uruguay,URY,14.374,57.69,High income,829.23606
181,United States,USA,12.500,84.20,High income,1052.50000
182,Uzbekistan,UZB,22.500,38.20,Lower middle income,859.50000
183,St. Vincent and the Grenadines,VCT,16.306,52.00,Upper middle income,847.91200
184,"Venezuela, RB",VEN,19.842,54.90,High income,1089.32580
185,Virgin Islands (U.S.),VIR,10.700,45.30,High income,484.71000
186,Vietnam,VNM,15.537,43.90,Lower middle income,682.07430
187,Vanuatu,VUT,26.739,11.30,Lower middle income,302.15070
188,West Bank and Gaza,PSE,30.394,46.60,Lower middle income,1416.36040
189,Samoa,WSM,26.172,15.30,Lower middle income,400.43160
190,"Yemen, Rep.",YEM,32.947,20.00,Lower middle income,658.94000
191,South Africa,ZAF,20.850,46.50,Upper middle income,969.52500
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income,93.26680
193,Zambia,ZMB,40.471,15.40,Lower middle income,623.25340
194,Zimbabwe,ZWE,35.715,18.50,Low income,660.72750

In [14]:
df.info() # into() gives information of data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [15]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [16]:
df[1:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [17]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [18]:
df[1:100:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9000,Low income
11,Burundi,BDI,44.151,1.3000,Low income
21,Belize,BLZ,23.092,33.6000,Upper middle income
31,Switzerland,CHE,10.200,86.3400,High income
41,Cuba,CUB,10.400,27.9300,Upper middle income
51,"Egypt, Arab Rep.",EGY,28.032,29.4000,Lower middle income
61,United Kingdom,GBR,12.200,89.8441,High income
71,Guatemala,GTM,27.465,19.7000,Lower middle income
81,Ireland,IRL,15.000,78.2477,High income
91,Kenya,KEN,35.194,39.0000,Lower middle income

In [19]:
df[10:21]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income
20,Belarus,BLR,12.500,54.17000,Upper middle income

In [20]:
df.describe() # describe() - Descriptive Statistics. This function display only numerical records.

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [21]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [22]:
df['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [23]:
df['CountryCode']

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [24]:
df[['CountryName',	'CountryCode', 'IncomeGroup']] # Categorical data(string)

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [25]:
df_cat = df[['CountryName',	'CountryCode', 'IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [26]:
print(len(df))
print(len(df_cat))

195
195

In [27]:
print(len(df.columns))
print(len(df_cat.columns))

5
3

In [28]:
print(df.columns)

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [29]:
print(df_cat.columns)

Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [30]:
df_cat.describe() # describe() on categorical data(string data)

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [31]:
df_num = df[['BirthRate','InternetUsers']]
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [33]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CountryName  195 non-null    object
 1   CountryCode  195 non-null    object
 2   IncomeGroup  195 non-null    object
dtypes: object(3)
memory usage: 4.7+ KB

In [34]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   BirthRate      195 non-null    float64
 1   InternetUsers  195 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB

In [35]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BirthRate,195.0,21.469928,10.605467,7.9,12.1205,19.68,29.7595,49.6610
InternetUsers,195.0,42.076471,29.030788,0.9,14.5200,41.00,66.2250,96.5468

In [36]:
df.describe().T # short form of df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BirthRate,195.0,21.469928,10.605467,7.9,12.1205,19.68,29.7595,49.6610
InternetUsers,195.0,42.076471,29.030788,0.9,14.5200,41.00,66.2250,96.5468

In [37]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [38]:
df.columns = ['a','b','c','d','e']
df

                        a    b       c     d                    e
0                   Aruba  ABW  10.244  78.9          High income
1             Afghanistan  AFG  35.253   5.9           Low income
2                  Angola  AGO  45.985  19.1  Upper middle income
3                 Albania  ALB  12.877  57.2  Upper middle income
4    United Arab Emirates  ARE  11.044  88.0          High income
..                    ...  ...     ...   ...                  ...
190           Yemen, Rep.  YEM  32.947  20.0  Lower middle income
191          South Africa  ZAF  20.850  46.5  Upper middle income
192      Congo, Dem. Rep.  COD  42.394   2.2           Low income
193                Zambia  ZMB  40.471  15.4  Lower middle income
194              Zimbabwe  ZWE  35.715  18.5           Low income

[195 rows x 5 columns]

In [39]:
df

                        a    b       c     d                    e
0                   Aruba  ABW  10.244  78.9          High income
1             Afghanistan  AFG  35.253   5.9           Low income
2                  Angola  AGO  45.985  19.1  Upper middle income
3                 Albania  ALB  12.877  57.2  Upper middle income
4    United Arab Emirates  ARE  11.044  88.0          High income
..                    ...  ...     ...   ...                  ...
190           Yemen, Rep.  YEM  32.947  20.0  Lower middle income
191          South Africa  ZAF  20.850  46.5  Upper middle income
192      Congo, Dem. Rep.  COD  42.394   2.2           Low income
193                Zambia  ZMB  40.471  15.4  Lower middle income
194              Zimbabwe  ZWE  35.715  18.5           Low income

[195 rows x 5 columns]

In [40]:
df.head(1)

       a    b       c     d            e
0  Aruba  ABW  10.244  78.9  High income

In [41]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers', 'IncomeGroup']
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [42]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [43]:
df[['CountryCode','BirthRate','InternetUsers']][4:8]

  CountryCode  BirthRate  InternetUsers
4         ARE     11.044           88.0
5         ARG     17.716           59.9
6         ARM     13.308           41.9
7         ATG     16.447           63.4

In [44]:
df[4:8][['CountryCode','BirthRate','InternetUsers']] #  x*y = y*x

  CountryCode  BirthRate  InternetUsers
4         ARE     11.044           88.0
5         ARG     17.716           59.9
6         ARM     13.308           41.9
7         ATG     16.447           63.4

In [45]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [46]:
df.BirthRate * df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [47]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [48]:
df['newcolumn'] = df.BirthRate * df.InternetUsers
df.head(6)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
5,Argentina,ARG,17.716,59.9,High income,1061.1884

In [49]:
len(df.columns)

6

In [50]:
df.drop('newcolumn', axis = 1)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [51]:
df.drop('newcolumn', axis = 1)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [52]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,658.9400
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

In [53]:
df.InternetUsers < 2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [54]:
df[df.InternetUsers < 2]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
11,Burundi,BDI,44.151,1.3,Low income,57.3963
52,Eritrea,ERI,34.800,0.9,Low income,31.3200
55,Ethiopia,ETH,32.925,1.9,Low income,62.5575
64,Guinea,GIN,37.337,1.6,Low income,59.7392
117,Myanmar,MMR,18.119,1.6,Lower middle income,28.9904
127,Niger,NER,49.661,1.7,Low income,84.4237
154,Sierra Leone,SLE,36.729,1.7,Low income,62.4393
156,Somalia,SOM,43.891,1.5,Low income,65.8365
172,Timor-Leste,TLS,35.755,1.1,Lower middle income,39.3305

In [55]:
len(df[df.InternetUsers < 2])

9

In [56]:
df[df.BirthRate > 40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
11,Burundi,BDI,44.151,1.3,Low income,57.3963
14,Burkina Faso,BFA,40.551,9.1,Low income,369.0141
65,"Gambia, The",GMB,42.525,14.0,Low income,595.3500
115,Mali,MLI,44.138,3.5,Low income,154.4830
127,Niger,NER,49.661,1.7,Low income,84.4237
128,Nigeria,NGA,40.045,38.0,Lower middle income,1521.7100
156,Somalia,SOM,43.891,1.5,Low income,65.8365
167,Chad,TCD,45.745,2.3,Low income,105.2135
178,Uganda,UGA,43.474,16.2,Low income,704.2788
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534

In [57]:
len(df[df.BirthRate > 40])

12

In [58]:
low_internetuser_country = df[df.InternetUsers < 2]
low_internetuser_country

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
11,Burundi,BDI,44.151,1.3,Low income,57.3963
52,Eritrea,ERI,34.800,0.9,Low income,31.3200
55,Ethiopia,ETH,32.925,1.9,Low income,62.5575
64,Guinea,GIN,37.337,1.6,Low income,59.7392
117,Myanmar,MMR,18.119,1.6,Lower middle income,28.9904
127,Niger,NER,49.661,1.7,Low income,84.4237
154,Sierra Leone,SLE,36.729,1.7,Low income,62.4393
156,Somalia,SOM,43.891,1.5,Low income,65.8365
172,Timor-Leste,TLS,35.755,1.1,Lower middle income,39.3305

In [59]:
high_birth_rate = df[df.BirthRate > 40]
high_birth_rate

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
11,Burundi,BDI,44.151,1.3,Low income,57.3963
14,Burkina Faso,BFA,40.551,9.1,Low income,369.0141
65,"Gambia, The",GMB,42.525,14.0,Low income,595.3500
115,Mali,MLI,44.138,3.5,Low income,154.4830
127,Niger,NER,49.661,1.7,Low income,84.4237
128,Nigeria,NGA,40.045,38.0,Lower middle income,1521.7100
156,Somalia,SOM,43.891,1.5,Low income,65.8365
167,Chad,TCD,45.745,2.3,Low income,105.2135
178,Uganda,UGA,43.474,16.2,Low income,704.2788
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534

In [60]:
df[(df.InternetUsers < 2) & (df.BirthRate > 40)]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup  newcolumn
11      Burundi         BDI     44.151            1.3  Low income    57.3963
127       Niger         NER     49.661            1.7  Low income    84.4237
156     Somalia         SOM     43.891            1.5  Low income    65.8365

In [61]:
Filter = df.InternetUsers < 2
Filter2 = df.BirthRate > 40
df[Filter & Filter2]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup  newcolumn
11      Burundi         BDI     44.151            1.3  Low income    57.3963
127       Niger         NER     49.661            1.7  Low income    84.4237
156     Somalia         SOM     43.891            1.5  Low income    65.8365

In [63]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,658.9400
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

In [70]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,185,186,187,188,189,190,191,192,193,194
CountryName,Aruba,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,Antigua and Barbuda,Australia,Austria,...,Virgin Islands (U.S.),Vietnam,Vanuatu,West Bank and Gaza,Samoa,"Yemen, Rep.",South Africa,"Congo, Dem. Rep.",Zambia,Zimbabwe
CountryCode,ABW,AFG,AGO,ALB,ARE,ARG,ARM,ATG,AUS,AUT,...,VIR,VNM,VUT,PSE,WSM,YEM,ZAF,COD,ZMB,ZWE
BirthRate,10.244,35.253,45.985,12.877,11.044,17.716,13.308,16.447,13.2,9.4,...,10.7,15.537,26.739,30.394,26.172,32.947,20.85,42.394,40.471,35.715
InternetUsers,78.9,5.9,19.1,57.2,88.0,59.9,41.9,63.4,83.0,80.6188,...,45.3,43.9,11.3,46.6,15.3,20.0,46.5,2.2,15.4,18.5
IncomeGroup,High income,Low income,Upper middle income,Upper middle income,High income,High income,Lower middle income,High income,High income,High income,...,High income,Lower middle income,Lower middle income,Lower middle income,Lower middle income,Lower middle income,Upper middle income,Low income,Lower middle income,Low income
newcolumn,808.2516,207.9927,878.3135,736.5644,971.872,1061.1884,557.6052,1042.7398,1095.6,757.81672,...,484.71,682.0743,302.1507,1416.3604,400.4316,658.94,969.525,93.2668,623.2534,660.7275

In [71]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,185,186,187,188,189,190,191,192,193,194
CountryName,Aruba,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,Antigua and Barbuda,Australia,Austria,...,Virgin Islands (U.S.),Vietnam,Vanuatu,West Bank and Gaza,Samoa,"Yemen, Rep.",South Africa,"Congo, Dem. Rep.",Zambia,Zimbabwe
CountryCode,ABW,AFG,AGO,ALB,ARE,ARG,ARM,ATG,AUS,AUT,...,VIR,VNM,VUT,PSE,WSM,YEM,ZAF,COD,ZMB,ZWE
BirthRate,10.244,35.253,45.985,12.877,11.044,17.716,13.308,16.447,13.2,9.4,...,10.7,15.537,26.739,30.394,26.172,32.947,20.85,42.394,40.471,35.715
InternetUsers,78.9,5.9,19.1,57.2,88.0,59.9,41.9,63.4,83.0,80.6188,...,45.3,43.9,11.3,46.6,15.3,20.0,46.5,2.2,15.4,18.5
IncomeGroup,High income,Low income,Upper middle income,Upper middle income,High income,High income,Lower middle income,High income,High income,High income,...,High income,Lower middle income,Lower middle income,Lower middle income,Lower middle income,Lower middle income,Upper middle income,Low income,Lower middle income,Low income
newcolumn,808.2516,207.9927,878.3135,736.5644,971.872,1061.1884,557.6052,1042.7398,1095.6,757.81672,...,484.71,682.0743,302.1507,1416.3604,400.4316,658.94,969.525,93.2668,623.2534,660.7275

In [72]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720
...,...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income,658.9400
191,South Africa,ZAF,20.850,46.5,Upper middle income,969.5250
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income,93.2668
193,Zambia,ZMB,40.471,15.4,Lower middle income,623.2534
194,Zimbabwe,ZWE,35.715,18.5,Low income,660.7275

In [79]:
df[0:3]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,newcolumn
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135

In [82]:
df = df.drop('newcolumn', axis=1)

In [83]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [94]:
df[0:3][df.columns[0:2]]

   CountryName CountryCode
0        Aruba         ABW
1  Afghanistan         AFG
2       Angola         AGO

In [103]:
df[0:4][df.columns[:]]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income

In [106]:
df[df.InternetUsers > 4][df.columns[0:3]]

              CountryName CountryCode  BirthRate
0                   Aruba         ABW     10.244
1             Afghanistan         AFG     35.253
2                  Angola         AGO     45.985
3                 Albania         ALB     12.877
4    United Arab Emirates         ARE     11.044
..                    ...         ...        ...
189                 Samoa         WSM     26.172
190           Yemen, Rep.         YEM     32.947
191          South Africa         ZAF     20.850
193                Zambia         ZMB     40.471
194              Zimbabwe         ZWE     35.715

[179 rows x 3 columns]

In [112]:
df[df.InternetUsers > 4][df.columns[0:3]].head(21)

               CountryName CountryCode  BirthRate
0                    Aruba         ABW     10.244
1              Afghanistan         AFG     35.253
2                   Angola         AGO     45.985
3                  Albania         ALB     12.877
4     United Arab Emirates         ARE     11.044
5                Argentina         ARG     17.716
6                  Armenia         ARM     13.308
7      Antigua and Barbuda         ATG     16.447
8                Australia         AUS     13.200
9                  Austria         AUT      9.400
10              Azerbaijan         AZE     18.300
12                 Belgium         BEL     11.200
13                   Benin         BEN     36.440
14            Burkina Faso         BFA     40.551
15              Bangladesh         BGD     20.142
16                Bulgaria         BGR      9.200
17                 Bahrain         BHR     15.040
18            Bahamas, The         BHS     15.339
19  Bosnia and Herzegovina         BIH      9.062
20                 Belarus         BLR     12.500
21                  Belize         BLZ     23.092

In [111]:
df[df.InternetUsers > 4][df.columns[0:3]].tail(21)

                        CountryName CountryCode  BirthRate
173                           Tonga         TON     25.409
174             Trinidad and Tobago         TTO     14.590
175                         Tunisia         TUN     19.800
176                          Turkey         TUR     16.836
177                        Tanzania         TZA     39.518
178                          Uganda         UGA     43.474
179                         Ukraine         UKR     11.100
180                         Uruguay         URY     14.374
181                   United States         USA     12.500
182                      Uzbekistan         UZB     22.500
183  St. Vincent and the Grenadines         VCT     16.306
184                   Venezuela, RB         VEN     19.842
185           Virgin Islands (U.S.)         VIR     10.700
186                         Vietnam         VNM     15.537
187                         Vanuatu         VUT     26.739
188              West Bank and Gaza         PSE     30.394
189                           Samoa         WSM     26.172
190                     Yemen, Rep.         YEM     32.947
191                    South Africa         ZAF     20.850
193                          Zambia         ZMB     40.471
194                        Zimbabwe         ZWE     35.715

In [113]:
df.head(24)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.90000,High income
1,Afghanistan,AFG,35.253,5.90000,Low income
2,Angola,AGO,45.985,19.10000,Upper middle income
3,Albania,ALB,12.877,57.20000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.00000,High income
5,Argentina,ARG,17.716,59.90000,High income
6,Armenia,ARM,13.308,41.90000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.40000,High income
8,Australia,AUS,13.200,83.00000,High income
9,Austria,AUT,9.400,80.61880,High income
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income
20,Belarus,BLR,12.500,54.17000,Upper middle income
21,Belize,BLZ,23.092,33.60000,Upper middle income
22,Bermuda,BMU,10.400,95.30000,High income
23,Bolivia,BOL,24.236,36.94000,Lower middle income

In [115]:
df[df.InternetUsers > 4][df.columns[0:3]].head(21).count()

CountryName    21
CountryCode    21
BirthRate      21
dtype: int64